name: Build Documentation

permissions:
    contents: read
    pages: write
    id-token: write

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Cache yarn packages
              uses: actions/cache@v3
              with:
                  path: |
                      .yarn/cache
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies & build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn
                  yarn build
                  yarn docs
                  echo "sdk.runcitadel.space" > docs/CNAME

            - name: Archive build output
              run: tar --dereference --hard-dereference --directory docs/ -cvf artifact.tar .

            - name: Upload Artifact
              uses: actions/upload-artifact@main
              with:
                name: github-pages
                path: ./artifact.tar
                if-no-files-found: warn

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
